### ISSUE TITLE
[Bug] Microsoft login not opening to browser on Linux

### ISSUE THREAD

**Issue by adamscafuto** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#104]
### Describe the bug

When attempting to add an account, clicking the Microsoft button does not open a browser and instead saves a file shown in the screenshot.

### To Reproduce

1. Launch the game.
2. Open the IGAS menu.
3. Click 'Add'.
4. Click 'Microsoft'.

### Minecraft Version

Forge 1.19.2

### Logs/Screenshots/Videos

https://i.imgur.com/t3ZGgCT.png

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by adamscafuto** [comment]
![image](https://user-images.githubusercontent.com/40708366/208741954-5b91fe52-dd7a-4d30-bc87-af755ceae82d.png)
Specs of System

**Comment by xFreakss** [comment]
Same on BigLinux, this also happens with links on in-game chat. Probably not plugin-side issue?

**Comment by VidTu** [comment]
Mod is opening login URL via Minecraft's [Util.getPlatform().openUri(String)](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/blob/cd83b4cf945b848279a42c0572b1cd547691f3bd/forge-1.14/src/main/java/the_fireplace/ias/gui/LoginScreen.java#L97) since 1.14 (I'm using [Desktop.getDesktop().browse(URI) with fallback to Sys.openURL(String)](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/blob/1bced5a7ef3164bba9d805dba1d8dcc25252e5ad/forge-1.12/src/main/java/the_fireplace/ias/gui/LoginScreen.java#L152) pre-1.14), so please test if you can open links via Minecraft chat before reporting any issues. I've tested the mod on a few Linux VMs (where I was able to find working drivers) like Ubuntu, Fedora and Manjaro and it opens URL in the default browser when configured.


###### You can use this command `/tellraw @s {"text":"Click me to open example URL.","clickEvent":{"action":"open_url","value":"https://example.org/"}}` in singleplayer to test URLs.

**Comment by xFreakss** [comment]
Not Happening anymore to me.

Openjdk 17.0.6
Mod version: v8.0.1.2
System:
![image](https://user-images.githubusercontent.com/89689590/232082359-a38ce45d-7313-4350-acd0-299c55dce69d.png)
