### ISSUE TITLE
Add default account selection when logging in

### ISSUE THREAD

**Issue by Wasdergingame** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#123]
### Related problem

Quite often I need to use a nickname that is different from my licensed account, and this mod helps a lot with this, but it is not always convenient to change the account every time I log into the game, especially if you use Quick to Play

### Describe the solution you'd like

It would be great if you added a default account selection feature

**Comment by VidTu** [comment]
i could've added this, but there's too many questions and too much clutter for this feature. for example, why. why should you switch to another account with this mod on startup and not use some prism launcher or other launcher with multiple accounts? microsoft authentication requires waiting, sometimes a lot (~10 seconds) on a bad internet with refreshing tokens. where should this waiting take place? on the loading screen? how to share authentication feedback? right after loading screen? how to make sure the player saw this and, for example, quick play connects to servers immediately, authentication requires waiting. how to properly select an account? how to select whether the online or offline mode is used? what to do if the account is no longer in the storage? what to do on errors? whether the quick play should be cancelled if we're unable to login (due to say, situations from previous two questions) or should it continue with the default account? what about compatibility with startup mods that display various fullscreen notices? what about v9 passkey encryption?

there are too many implementation details (and possibly clutter in the config or in the account switcher, alongside with confusion regarding this feature if users won't be given a description tooltip that won't fit into their screens) for seemingly useless feature. the simplest solution is to use some kind of modded launcher or just use the mod to log in into the account after startup.

i'm pretty much against implementing this as there're too many questions that you may answer, but the answers won't be universal for all people
