### ISSUE TITLE
[Feature] Support custom yggdrasil

### ISSUE THREAD

**Issue by LittleChest** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#134]
### Related problem

Some server request custom yggdrasil to play their server

### Describe the solution you'd like

Add a option to custom yggdrasil address
then the same with mojang account

**Comment by VidTu** [comment]
I've fully removed support for Legacy (Yggdrasil) Mojang auth due to it no longer functioning. ([authserver](https://authserver.mojang.com/authenticate) returns [HTTP-410](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410) for root and other endpoints, see picture below) Custom implementations require their own authlib and possibly readding Yggdrasil authentication protocol back or using deprecated methods from authlib, these are no longer used and can be removed in the future. I'm not going to implement any third-party authentication protocols into the mod. You're free to Mixin various mod APIs (or, say, extend the `Account` class) and add third-party authentication system if you want it.

![image](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/60929459/d10fa5be-23cd-464f-b483-11eaec67dcad)
