### ISSUE TITLE
[SUGGESTION] FancyMenu support

### ISSUE THREAD

**Issue by Camawama** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#140]
It appears that I am unable to remove or modify the text using FancyMenu.

**Comment by VidTu** [comment]
I didn't find any developer documentation [here](https://docs.fancymenu.net/) or API to implement from [here](https://github.com/Keksuccino/FancyMenu/tree/v3-1.20.4). (it's a little bit [painful](https://github.com/Keksuccino/FancyMenu/commits/v3-1.20.4/) to try to find something)

Due to how Minecraft renders text, mods can't usually control each others labels unless specific handling has been added for each mod. You can disable or move the text via built-in config, which can be opened through mods list on Forge and ModMenu on Fabric though.

**Comment by Camawama** [comment]
thank you for the info!
