### ISSUE TITLE
Me Have Problem with my premium account

### ISSUE THREAD

**Issue by Dawidek1** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#146]
![image](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/75498812/d60f5aa2-372c-4509-87ee-633b631f25c6)
I Use a version of account switcher 8.0.2

How to Fix IT?

**Comment by VidTu** [comment]
update to 9.0.0

**Comment by Dawidek1** [comment]
I Updated and me have this error

![image](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/75498812/c8ee61b1-0f5d-4100-8dc3-4f6a01c90121)

**Comment by SundayMC** [comment]
Hm, I have the same problem as the OP.

No matter how many times I delete and restore my accounts, it keeps telling me that the password is incorrect...

**Comment by VidTu** [comment]
there are some root problems with that sort of issues with IAS:
- logs need to be shared with developer (i.e. me) to understand what needs to be fixed. i can't simply look at the generic "unexpected error" screen and magically understand what's wrong. on the other hand, they should *not* be public (as the error screen) says, because they may or may not contain identifiable information. however, if anyone was to share their logs with me, that would probably include some logs encryption (with gpg or similar) which is not ideal. lastly, there is a trust factor. while logs probably won't contain identifiable information and i swear i'm not going to use them for anything but fixing bugs, why people should trust this? trusting random people in the security area (which logs that might contain tokens might be a part of) is a [generally bad idea](https://tukaani.org/xz-backdoor/).
- these issues aren't exactly reproducable and fixable. even if you shared logs in the most secure way possible and even though i do own a few microsoft/minecraft accounts, i'm not sure if i'll be able to fix that for example if microsoft just returns "404" and nothing else in the response body.

anyway, i'll write a doc how to share logs with me securely (if people would like to trust their logs to me) and will inform you how to do this then. (if you choose not to trust me, you're on your own with your problems)

**Comment by VidTu** [comment]
i've written a simple [guide](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/blob/main/docs/LOG_SHARING.md) on how to "securely" share logs. please, do so.

**Comment by VidTu** [comment]
no response.
