### ISSUE TITLE
[request]import from launcher

### ISSUE THREAD

**Issue by kittenvr** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#162]
allow to import accounts from diferent launchers like prism launcher

**Comment by VidTu** [comment]
Importing accounts from launchers won't be added for these reasons:
1. Security: Importing and using tokens poses a security risk.
2. Compatibility: We can't use launcher tokens because they're using a different application ID, that is, they're shown [here](https://account.live.com/consent/manage) as different apps and therefore we should use their UUIDs, which is bad for...
3. Legal issues: This is probably not allowed by Microsoft ToS and may be flagged as malware-alike behavior.
