### ISSUE TITLE
Pls make the mod for 1.21.1

### ISSUE THREAD

**Issue by shinenodes** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#172]

**Comment by Oregano1963** [comment]
for now, you can change the fabric mod.json. The minecraft version should be changed to 1.21.1 in a text editor.

**Comment by shinenodes** [comment]
idk how to do it

**Comment by BlueFox0010** [comment]
[https://www.mediafire.com/file/9ezzdsjruy8ogpl/IAS-Fabric-1.21.1-9.0.2-SNAPSHOT.jar/file](url)
use this

**Comment by VidTu** [comment]
Alpha builds for 1.21.1 and 1.21.3 have been uploaded to Modrinth. They aren't (and won't be) available on CurseForge and GitHub due to the fact I don't want to manually upload and mark loaders for 35 files (there are 35 mod files for all loaders for all versions). See #185 for details about CurseForge and GitHub.
