### ISSUE TITLE
[Feature request] Add ability to specify custom UUID on offline account

### ISSUE THREAD

**Issue by iocmet** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#180]

**Comment by VidTu** [comment]
I don't see the reasoning behind this feature.
There are some reasons against this feature though:
1. Offline UUIDs are currently conventionally created. Current method of creating offline UUIDs resembles the vanilla server in the offline mode and is used by practically any server and launcher. This includes Vanilla, Forge, Fabric, Quilt, NeoForge, Spigot, Paper, Purpur, BungeeCord, Velocity, etc. servers and client launchers like Prism Launcher.
2. There's no practical reason for this. Modern (1.19.1+) offline-mode servers won't process client UUIDs, they generate an offline player UUID on their own. Legacy offline-mode servers won't even receive client UUIDs, because there's no protocol to send that. In Singleplayer (the integrated server), data is stored independently of your current account.
3. Some Minecraft anti-bot solutions will gracefully say "GTFO" to these UUID manipulations.
4. Other mods may break because of this.

**Comment by VidTu** [comment]
There's no practical reason for this feature to be added, so this is not going to be implemented.

**Comment by VidTu** [comment]
the server never trusts the client's UUIDs and, as I've said, in older versions doesn't even receive them
