### ISSUE TITLE
Support for Minecraft 1.21.3

### ISSUE THREAD

**Issue by Yamato320** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#182]
An update of the Mod to the latest version of Minecraft, which is 1.21.3.

**Comment by BlueFox0010** [comment]
[https://www.mediafire.com/file/mw19abnbc6ad3xx/IAS-Fabric-1.21.3-9.0.2-SNAPSHOT.jar/file](url)
use this

**Comment by VidTu** [comment]
Alpha builds for 1.21.1 and 1.21.3 have been uploaded to Modrinth. They aren't (and won't be) available on CurseForge and GitHub due to the fact I don't want to manually upload and mark loaders for 35 files (there are 35 mod files for all loaders for all versions). See #185 for details about CurseForge and GitHub.
