### ISSUE TITLE
Button not showing

### ISSUE THREAD

**Issue by MHashirShahzad** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#183]
Hye, the button does not show here
![image](https://github.com/user-attachments/assets/a4d0cdc1-0261-4d67-848a-4e724d44c674)
can u add a shortcut key ?
![image](https://github.com/user-attachments/assets/e0fec53f-894f-48a7-9bfb-d31d59cbf21e)

**Comment by VidTu** [comment]
Support for Lunar and Feather is limited, because they don't have an API for mods. At least I can't find one [here](https://feathermc.com/) and [here](https://www.lunarclient.com/) (and [here](https://lunarclient.dev/) for that matter). **While I might attempt to fix this issue, please use clients' built-in account switcher or ask client developers to support this mod.**

**Comment by MHashirShahzad** [comment]
I have found an alternative, go to multiplayer, the account switch button is availible in multiplayer option, just not in main menu

**Comment by VidTu** [comment]
Nevertheless, Feather and Lunar won't be officially supported. That is, if mod's not working on these clients, I'm not going to (and most likely can't) fix any possible issues.
