### ISSUE TITLE
Can't log in or add a Microsoft account

### ISSUE THREAD

**Issue by ruben1PvP** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#51]
**Describe the bug**
I can't add or log in a Microsoft account 

**To Reproduce**
1. Enter the mod
2. Try to log into a Microsoft migrated account
3. Click "Add account"
4. Select "Microsoft" 
5. Authorize the mod to use your Microsoft account
6. Go back to your Minecraft. The same error will appear 

**Logs/Screenshots/Videos**
Screenshot of the error: https://exploit.sbs/DhKypAwU
Log: https://pastebin.com/YdPmGYQf
**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.8.9
 - Mod Version: 7.1.3
 - Loader type: Forge
 - Loader version. Forge 11.15.1.2318 (I don't know if this is what the template means)

**Comment by P0keDev** [comment]
it seems like this issue is caused by some missing certificates in minecraft's bundled java runtime - which is why it only occurs on older versions of minecraft that use java 8. i was able to fix it by specifying a different java 8 executable in the launcher's profile options. if you have a java 8 runtime installed, you can select it in installations -> edit -> more options -> java executable (default java location should be `C:/Program Files/Java/jre1.8.0_xxx/bin/javaw.exe` on windows)

**Comment by ruben1PvP** [comment]
> it seems like this issue is caused by some missing certificates in minecraft's bundled java runtime - which is why it only occurs on older versions of minecraft that use java 8. i was able to fix it by specifying a different java 8 executable in the launcher's profile options. if you have a java 8 runtime installed, you can select it in installations -> edit -> more options -> java executable (default java location should be `C:/Program Files/Java/jre1.8.0_xxx/bin/javaw.exe` on windows)

Thank you so much, it worked.
