### ISSUE TITLE
Relogging option doesn't work

### ISSUE THREAD

**Issue by TOLoneWolf** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#7]
"# Enables logging in to the account you are already logged in to.
B:ias.cfg.enablerelog=true"

When I enable this option in the config it doesn't let me relog with the same account with this error message: "You are already logged in to this account."

And a minor version issue on curse lets you install the mod for 1.11 but requires 1.11.2 on the curse client.

**Comment by The-Fireplace** [comment]
Try disabling it, see if it lets you then. It could be that something got
reversed in a patch someone else made.
And I will make sure my next build for 1.11 accepts both 1.11 and 1.11.2.

On Jan 6, 2017 9:50 PM, "TOLoneWolf" <notifications@github.com> wrote:

"# Enables logging in to the account you are already logged in to.
B:ias.cfg.enablerelog=true"

When I enable this option in the config it doesn't let me relog with the
same account with this error message: "You are already logged in to this
account."

And a minor version issue on curse lets you install the mod for 1.11 but
requires 1.11.2 on the curse client.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/The-Fireplace/In-Game-Account-Switcher/issues/7>, or mute
the thread

**Comment by TOLoneWolf** [comment]
Doesn't seem to matter what the option is set to it gives the same message.

**Comment by The-Fireplace** [comment]
Alright, thanks.

**Comment by VidTuGit** [comment]
Fixed in 7.0.6.
