### ISSUE TITLE
[Feature] 8.0.0 backport to 1.19?

### ISSUE THREAD

**Issue by kirmerk1** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#79]
### Related problem

Thanks for the 8.0.0 update, but it works only on 1.19.2. Is it possible to make it compatible with 1.19? A lot of people don't want to switch to 1.19.1/1.19.2 due to awful Microsoft/Mojang decisions.

### Describe the solution you'd like

1.19 compability.

### Additional context

Thanks.

**Comment by VidTu** [comment]
I don't really want to backport anything to older minor/patch versions just because I always support updating to latest patch version. I'm against Mojang decisions in 1.19.1, but I've never seen any server actively supporting it. Most servers that I play on don't require sending public profile key (you can avoid sending it via mods like [this](https://modrinth.com/mod/no-chat-reports)) and all servers that I play on send messages as SYSTEM_MESSAGE instead of CHAT, so messages are impossible to report.

**Comment by akemin-dayo** [comment]
The good news is that IAS is _extremely_ easy to backport to 1.19 — I already got it working, at least on Quilt/Fabric. (I haven't tried backporting to Forge 41.1.0 and 41.0.63 yet.)

@VidTu Would you like me to submit a PR to upstream the 1.19 backport? Or would you rather this remain strictly as an unofficial fork?

---

### Additional compatible versions (no code changes/backporting required)
* **IAS 8.0.0 for 1.19.2** is compatible with **1.19.1** on both Quilt/Fabric and Forge!
	* For Forge, you will need to modify the `mods.toml` file and change `loaderVersion` to `loaderVersion = "[42,)"`.
		* If you don't want to bother building from source, you can also do this by just modifying the prebuilt JAR file.
		* ※ I will probably submit a PR to upstream this change (as long as VidTu is open to it…?) since it requires no other code modifications — it just works™.)
		* I am aware that unlike 1.18.1, there aren't many people who will be using 1.19.1 (as 1.19.2 is protocol-compatible), but I think it's still a good idea to remove the version restriction if there's no reason for it to be there.
* **IAS 8.0.0 for 1.18.2** is compatible with **1.18.1** on both Fabric and Forge!
	* For Forge, you will need to modify the `mods.toml` file and change `loaderVersion` to `loaderVersion = "[39,)"`.
		* If you don't want to bother building from source, you can also do this by just modifying the prebuilt JAR file.
		* ※ I will probably submit a PR to upstream this change (as long as VidTu is open to it…?) since it requires no other code modifications — it just works™.)

**Comment by VidTu** [comment]
I don't see reason to update for older Forge 1.19 version, but other than that, go for it

**Comment by akemin-dayo** [comment]
The Forge refactors that happened at 41.0.64 and 41.0.94 means that a lot of people using Forge on 1.19 are somewhat stuck on 41.0.63 due to some mods (including IAS prior to today ;P) not updating to accommodate the new changes, so there's quite a significant number of people using that version.

And okay, I'll submit the PR, then!

**Comment by akemin-dayo** [comment]
(※ Apologies for the double-post, just wanted to make sure you'd see this question.)

For the PR, should I rename the subproject used for >=1.19.1 to something like `fabric-1.19.x` or `fabric-1.19.2`?

The reason why I ask is because having a subproject named `fabric-1.19` that is only compatible with >=1.19.1 (and given the existence of the oddly-named `fabric-1.19-backport`) would probably come off as confusing to any would-be contributors.

**Comment by akemin-dayo** [comment]
@kirmerk1 **If you don't want to build IAS yourself, and you trust me / are comfortable running unofficial binaries from me**, see below for some prebuilt jars for 1.19 (and a few other versions) that you can just drop into your `mods/` folder.

---

## If you're just a normal user (non-developer) coming across this post…

**If you don't want to build IAS yourself, and you trust me / are comfortable running unofficial binaries from me**, here are some prebuilt jars that you can just drop into your `mods/` folder:

### 1.19

* **IAS 8.0.0~akemi for Quilt/Fabric 1.19:** https://developer.akemi.ai/Minecraft/InGameAccountSwitcher-Fabric-1.19-8.0.0~akemi.jar
* **IAS 8.0.0~akemi for Forge 1.19 (41.0.94 and above):** https://developer.akemi.ai/Minecraft/InGameAccountSwitcher-Forge-1.19-8.0.0~akemi.jar
* **IAS 8.0.0~akemi for Forge 1.19 (41.0.63 and below):** https://developer.akemi.ai/Minecraft/InGameAccountSwitcher-Forge-1.19-41.0.63-8.0.0~akemi.jar

### 1.19.2, 1.19.1

* **IAS 8.0.0~akemi for Quilt/Fabric 1.19.2 and 1.19.1:** https://developer.akemi.ai/Minecraft/InGameAccountSwitcher-Fabric-1.19.2-1.19.1-8.0.0~akemi.jar
* **IAS 8.0.0~akemi for Forge 1.19.2 and 1.19.1:** https://developer.akemi.ai/Minecraft/InGameAccountSwitcher-Forge-1.19.2-1.19.1-8.0.0~akemi.jar

### 1.18.2, 1.18.1, 1.18

* **IAS 8.0.0~akemi for Forge 1.18.2, 1.18.1, and 1.18:** https://developer.akemi.ai/Minecraft/InGameAccountSwitcher-Forge-1.18-8.0.0~akemi.jar

**Comment by kirmerk1** [comment]
@akemin-dayo Wow, that was fast. Thank you. Works great.

**Comment by VidTu** [comment]
Technically fixed, but I'll pin this issue until publishing to CF and ModRinth.

**Comment by akemin-dayo** [comment]
Seems like 8.0.1 removed the backports again. I'll update my fork for 8.0.1 sometime today.

**Comment by VidTu** [comment]
I've rethought my position about publishing backported versions to CF/ModRinth because I don't see any reason to use 1.19 (and old minor versions and pretty much all Forge 1.19-41.0.63 have updated to 1.19.1/1.19.2), if you don't want to be chat-reported just use NoChatReports mod on 1.19.2. Someday Mojang will release 1.20 and you'll need to play 1.20 with chat reports. You can continue to update your fork if you want. (Well, nothing stops you from updating it, mod is licensed under LGPL)

**Comment by akemin-dayo** [comment]
Fair enough — my concern never really was with chat reporting to begin with (I always use NCR on any version >= 1.19.1 ;P).

I just personally hold the belief that if supporting older versions is really simple to do, there's no reason _not_ for me to do so. …Which is my approach to software development in general — my iOS tweaks stretch back as far as iOS 5 whenever possible ;P

Judging by your response, I assume I shouldn't bother submitting a PR, then?

I will suggest one thing though — it would probably be a good idea to re-add the version locks for 1.19 on your 1.19.1/2 `fabric.mod.json` and `mods.toml` (require Forge Loader version >= 42) metadata files, as seen here:

https://github.com/akemin-dayo/In-Game-Account-Switcher/blob/main/fabric-1.19/src/main/resources/fabric.mod.json#L38-L40

https://github.com/akemin-dayo/In-Game-Account-Switcher/blob/eb9820e89b6edbf391592df152e8ef435f89c871/forge-1.19/src/main/resources/META-INF/mods.toml#L2
